//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'MasterWorklog'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class MasterWorklog : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="MasterWorklog"/> class.</summary>
		public MasterWorklog() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the AuthorEmailAddress field. </summary>
		[DataMember]
		public System.String AuthorEmailAddress { get; set;}
		/// <summary>Gets or sets the AuthorKey field. </summary>
		[DataMember]
		public System.String AuthorKey { get; set;}
		/// <summary>Gets or sets the AuthorName field. </summary>
		[DataMember]
		public System.String AuthorName { get; set;}
		/// <summary>Gets or sets the Comment field. </summary>
		[DataMember]
		public System.String Comment { get; set;}
		/// <summary>Gets or sets the DateCreated field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateCreated { get; set;}
		/// <summary>Gets or sets the DateStarted field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateStarted { get; set;}
		/// <summary>Gets or sets the DateUpdated field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateUpdated { get; set;}
		/// <summary>Gets or sets the IssueId field. </summary>
		[DataMember]
		public System.String IssueId { get; set;}
		/// <summary>Gets or sets the MasterWorklogId field. </summary>
		[DataMember]
		public System.Int32 MasterWorklogId { get; set;}
		/// <summary>Gets or sets the RecordDateCreated field. </summary>
		[DataMember]
		public System.DateTime RecordDateCreated { get; set;}
		/// <summary>Gets or sets the RecordDateUpdated field. </summary>
		[DataMember]
		public System.DateTime RecordDateUpdated { get; set;}
		/// <summary>Gets or sets the RecordState field. </summary>
		[DataMember]
		public System.String RecordState { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Gets or sets the TimeSpentSeconds field. </summary>
		[DataMember]
		public Nullable<System.Int64> TimeSpentSeconds { get; set;}
		/// <summary>Gets or sets the WebHookEvent field. </summary>
		[DataMember]
		public System.String WebHookEvent { get; set;}
		/// <summary>Gets or sets the WorkLogId field. </summary>
		[DataMember]
		public System.String WorkLogId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterWorklog.SyncSystem - SyncSystem.MasterWorklogs (m:1)'</summary>
		[DataMember]
		public virtual SyncSystem SyncSystem { get; set;}
		#endregion
	}
}
