//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'MasterFieldMappingValue'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class MasterFieldMappingValue : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="MasterFieldMappingValue"/> class.</summary>
		public MasterFieldMappingValue() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the MasterFieldMappingValueId field. </summary>
		[DataMember]
		public System.Int32 MasterFieldMappingValueId { get; set;}
		/// <summary>Gets or sets the MasterId field. </summary>
		[DataMember]
		public System.Int32 MasterId { get; set;}
		/// <summary>Gets or sets the SyncSystemFieldMappingId field. </summary>
		[DataMember]
		public System.Int32 SyncSystemFieldMappingId { get; set;}
		/// <summary>Gets or sets the Value field. </summary>
		[DataMember]
		public System.String Value { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterFieldMappingValue.Master - Master.MasterFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual Master Master { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterFieldMappingValue.SyncSystemFieldMapping - SyncSystemFieldMapping.MasterFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual SyncSystemFieldMapping SyncSystemFieldMapping { get; set;}
		#endregion
	}
}
