//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'MasterHistoryFieldMappingValue'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class MasterHistoryFieldMappingValue : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="MasterHistoryFieldMappingValue"/> class.</summary>
		public MasterHistoryFieldMappingValue() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the MasterHistoryFieldMappingValueId field. </summary>
		[DataMember]
		public System.Int32 MasterHistoryFieldMappingValueId { get; set;}
		/// <summary>Gets or sets the MasterHistoryId field. </summary>
		[DataMember]
		public System.Int32 MasterHistoryId { get; set;}
		/// <summary>Gets or sets the SyncSystemFieldMappingId field. </summary>
		[DataMember]
		public System.Int32 SyncSystemFieldMappingId { get; set;}
		/// <summary>Gets or sets the Value field. </summary>
		[DataMember]
		public System.String Value { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterHistoryFieldMappingValue.MasterHistory - MasterHistory.MasterHistoryFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual MasterHistory MasterHistory { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterHistoryFieldMappingValue.SyncSystemFieldMapping - SyncSystemFieldMapping.MasterHistoryFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual SyncSystemFieldMapping SyncSystemFieldMapping { get; set;}
		#endregion
	}
}
