//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'Master'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class Master : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="Master"/> class.</summary>
		public Master() : base()
		{
			this.MasterFieldMappingValues = new HashSet<MasterFieldMappingValue>();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the Assignee field. </summary>
		[DataMember]
		public System.String Assignee { get; set;}
		/// <summary>Gets or sets the DateFinish field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateFinish { get; set;}
		/// <summary>Gets or sets the DateFinishActual field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateFinishActual { get; set;}
		/// <summary>Gets or sets the DateRelease field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateRelease { get; set;}
		/// <summary>Gets or sets the DateStart field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateStart { get; set;}
		/// <summary>Gets or sets the DateStartActual field. </summary>
		[DataMember]
		public Nullable<System.DateTime> DateStartActual { get; set;}
		/// <summary>Gets or sets the IsSubTask field. </summary>
		[DataMember]
		public System.Boolean IsSubTask { get; set;}
		/// <summary>Gets or sets the IssueActualWork field. </summary>
		[DataMember]
		public Nullable<System.Int32> IssueActualWork { get; set;}
		/// <summary>Gets or sets the IssueId field. </summary>
		[DataMember]
		public System.String IssueId { get; set;}
		/// <summary>Gets or sets the IssueKey field. </summary>
		[DataMember]
		public System.String IssueKey { get; set;}
		/// <summary>Gets or sets the IssueName field. </summary>
		[DataMember]
		public System.String IssueName { get; set;}
		/// <summary>Gets or sets the IssueStatus field. </summary>
		[DataMember]
		public System.String IssueStatus { get; set;}
		/// <summary>Gets or sets the IssueTypeId field. </summary>
		[DataMember]
		public System.String IssueTypeId { get; set;}
		/// <summary>Gets or sets the IssueTypeName field. </summary>
		[DataMember]
		public System.String IssueTypeName { get; set;}
		/// <summary>Gets or sets the MasterId field. </summary>
		[DataMember]
		public System.Int32 MasterId { get; set;}
		/// <summary>Gets or sets the OriginalEstimate field. </summary>
		[DataMember]
		public Nullable<System.Int32> OriginalEstimate { get; set;}
		/// <summary>Gets or sets the ParentEpicId field. </summary>
		[DataMember]
		public System.String ParentEpicId { get; set;}
		/// <summary>Gets or sets the ParentEpicKey field. </summary>
		[DataMember]
		public System.String ParentEpicKey { get; set;}
		/// <summary>Gets or sets the ParentIssueId field. </summary>
		[DataMember]
		public System.String ParentIssueId { get; set;}
		/// <summary>Gets or sets the ParentIssueKey field. </summary>
		[DataMember]
		public System.String ParentIssueKey { get; set;}
		/// <summary>Gets or sets the ParentSprintId field. </summary>
		[DataMember]
		public System.String ParentSprintId { get; set;}
		/// <summary>Gets or sets the ParentSprintName field. </summary>
		[DataMember]
		public System.String ParentSprintName { get; set;}
		/// <summary>Gets or sets the ParentVersionId field. </summary>
		[DataMember]
		public System.String ParentVersionId { get; set;}
		/// <summary>Gets or sets the ParentVersionName field. </summary>
		[DataMember]
		public System.String ParentVersionName { get; set;}
		/// <summary>Gets or sets the ParentVersionReleased field. </summary>
		[DataMember]
		public Nullable<System.Boolean> ParentVersionReleased { get; set;}
		/// <summary>Gets or sets the ProjectId field. </summary>
		[DataMember]
		public System.String ProjectId { get; set;}
		/// <summary>Gets or sets the ProjectKey field. </summary>
		[DataMember]
		public System.String ProjectKey { get; set;}
		/// <summary>Gets or sets the ProjectName field. </summary>
		[DataMember]
		public System.String ProjectName { get; set;}
		/// <summary>Gets or sets the RecordDateCreated field. </summary>
		[DataMember]
		public System.DateTime RecordDateCreated { get; set;}
		/// <summary>Gets or sets the RecordDateUpdated field. </summary>
		[DataMember]
		public System.DateTime RecordDateUpdated { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterFieldMappingValue.Master - Master.MasterFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual ICollection<MasterFieldMappingValue> MasterFieldMappingValues { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Master.SyncSystem - SyncSystem.Masters (m:1)'</summary>
		[DataMember]
		public virtual SyncSystem SyncSystem { get; set;}
		#endregion
	}
}
