//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'StagingFieldMappingValue'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class StagingFieldMappingValue : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="StagingFieldMappingValue"/> class.</summary>
		public StagingFieldMappingValue() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the StagingFieldMappingValueId field. </summary>
		[DataMember]
		public System.Int32 StagingFieldMappingValueId { get; set;}
		/// <summary>Gets or sets the StagingId field. </summary>
		[DataMember]
		public System.Int32 StagingId { get; set;}
		/// <summary>Gets or sets the SyncSystemFieldMappingId field. </summary>
		[DataMember]
		public System.Int32 SyncSystemFieldMappingId { get; set;}
		/// <summary>Gets or sets the Value field. </summary>
		[DataMember]
		public System.String Value { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'StagingFieldMappingValue.Staging - Staging.StagingFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual Staging Staging { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'StagingFieldMappingValue.SyncSystemFieldMapping - SyncSystemFieldMapping.StagingFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual SyncSystemFieldMapping SyncSystemFieldMapping { get; set;}
		#endregion
	}
}
