//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'SyncSystemType'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class SyncSystemType : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="SyncSystemType"/> class.</summary>
		public SyncSystemType() : base()
		{
			this.SyncSystems = new HashSet<SyncSystem>();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the SystemTypeId field. </summary>
		[DataMember]
		public System.Int32 SystemTypeId { get; set;}
		/// <summary>Gets or sets the SystemTypeName field. </summary>
		[DataMember]
		public System.String SystemTypeName { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystem.SyncSystemType - SyncSystemType.SyncSystems (m:1)'</summary>
		[DataMember]
		public virtual ICollection<SyncSystem> SyncSystems { get; set;}
		#endregion
	}
}
