//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'SyncSystemSetting'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class SyncSystemSetting : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="SyncSystemSetting"/> class.</summary>
		public SyncSystemSetting() : base()
		{
			this.SyncSystemSettingValues = new HashSet<SyncSystemSettingValue>();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the Setting field. </summary>
		[DataMember]
		public System.String Setting { get; set;}
		/// <summary>Gets or sets the SettingId field. </summary>
		[DataMember]
		public System.Int32 SettingId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystemSettingValue.SyncSystemSetting - SyncSystemSetting.SyncSystemSettingValues (m:1)'</summary>
		[DataMember]
		public virtual ICollection<SyncSystemSettingValue> SyncSystemSettingValues { get; set;}
		#endregion
	}
}
