//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'SyncSystem'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class SyncSystem : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="SyncSystem"/> class.</summary>
		public SyncSystem() : base()
		{
			this.Masters = new HashSet<Master>();
			this.MasterHistories = new HashSet<MasterHistory>();
			this.MasterWorklogs = new HashSet<MasterWorklog>();
			this.ProjectServerSystemLinks = new HashSet<ProjectServerSystemLink>();
			this.Stagings = new HashSet<Staging>();
			this.SyncSystemFieldMappings = new HashSet<SyncSystemFieldMapping>();
			this.SyncSystemSettingValues = new HashSet<SyncSystemSettingValue>();
			this.WebHookEntries = new HashSet<WebHookEntry>();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the DefaultParentTaskName field. </summary>
		[DataMember]
		public System.String DefaultParentTaskName { get; set;}
		/// <summary>Gets or sets the SystemApiUrl field. </summary>
		[DataMember]
		public System.String SystemApiUrl { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Gets or sets the SystemLogin field. </summary>
		[DataMember]
		public System.String SystemLogin { get; set;}
		/// <summary>Gets or sets the SystemName field. </summary>
		[DataMember]
		public System.String SystemName { get; set;}
		/// <summary>Gets or sets the SystemPassword field. </summary>
		[DataMember]
		public System.String SystemPassword { get; set;}
		/// <summary>Gets or sets the SystemTypeId field. </summary>
		[DataMember]
		public System.Int32 SystemTypeId { get; set;}
		/// <summary>Gets or sets the SystemUrl field. </summary>
		[DataMember]
		public System.String SystemUrl { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Master.SyncSystem - SyncSystem.Masters (m:1)'</summary>
		[DataMember]
		public virtual ICollection<Master> Masters { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterHistory.SyncSystem - SyncSystem.MasterHistories (m:1)'</summary>
		[DataMember]
		public virtual ICollection<MasterHistory> MasterHistories { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterWorklog.SyncSystem - SyncSystem.MasterWorklogs (m:1)'</summary>
		[DataMember]
		public virtual ICollection<MasterWorklog> MasterWorklogs { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'ProjectServerSystemLink.SyncSystem - SyncSystem.ProjectServerSystemLinks (m:1)'</summary>
		[DataMember]
		public virtual ICollection<ProjectServerSystemLink> ProjectServerSystemLinks { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'Staging.SyncSystem - SyncSystem.Stagings (m:1)'</summary>
		[DataMember]
		public virtual ICollection<Staging> Stagings { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystemFieldMapping.SyncSystem - SyncSystem.SyncSystemFieldMappings (m:1)'</summary>
		[DataMember]
		public virtual ICollection<SyncSystemFieldMapping> SyncSystemFieldMappings { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystemSettingValue.SyncSystem - SyncSystem.SyncSystemSettingValues (m:1)'</summary>
		[DataMember]
		public virtual ICollection<SyncSystemSettingValue> SyncSystemSettingValues { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystem.SyncSystemType - SyncSystemType.SyncSystems (m:1)'</summary>
		[DataMember]
		public virtual SyncSystemType SyncSystemType { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'WebHookEntry.SyncSystem - SyncSystem.WebHookEntries (m:1)'</summary>
		[DataMember]
		public virtual ICollection<WebHookEntry> WebHookEntries { get; set;}
		#endregion
	}
}
