//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'SyncSystemFieldMapping'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class SyncSystemFieldMapping : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="SyncSystemFieldMapping"/> class.</summary>
		public SyncSystemFieldMapping() : base()
		{
			this.MasterFieldMappingValues = new HashSet<MasterFieldMappingValue>();
			this.MasterHistoryFieldMappingValues = new HashSet<MasterHistoryFieldMappingValue>();
			this.StagingFieldMappingValues = new HashSet<StagingFieldMappingValue>();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the EpmFieldName field. </summary>
		[DataMember]
		public System.String EpmFieldName { get; set;}
		/// <summary>Gets or sets the FieldType field. </summary>
		[DataMember]
		public System.String FieldType { get; set;}
		/// <summary>Gets or sets the IsIdWithValue field. </summary>
		[DataMember]
		public System.Boolean IsIdWithValue { get; set;}
		/// <summary>Gets or sets the IsMultiSelect field. </summary>
		[DataMember]
		public System.Boolean IsMultiSelect { get; set;}
		/// <summary>Gets or sets the StagingFieldName field. </summary>
		[DataMember]
		public System.String StagingFieldName { get; set;}
		/// <summary>Gets or sets the SyncSystemFieldMappingId field. </summary>
		[DataMember]
		public System.Int32 SyncSystemFieldMappingId { get; set;}
		/// <summary>Gets or sets the SystemFieldName field. </summary>
		[DataMember]
		public System.String SystemFieldName { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterFieldMappingValue.SyncSystemFieldMapping - SyncSystemFieldMapping.MasterFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual ICollection<MasterFieldMappingValue> MasterFieldMappingValues { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'MasterHistoryFieldMappingValue.SyncSystemFieldMapping - SyncSystemFieldMapping.MasterHistoryFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual ICollection<MasterHistoryFieldMappingValue> MasterHistoryFieldMappingValues { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'StagingFieldMappingValue.SyncSystemFieldMapping - SyncSystemFieldMapping.StagingFieldMappingValues (m:1)'</summary>
		[DataMember]
		public virtual ICollection<StagingFieldMappingValue> StagingFieldMappingValues { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystemFieldMapping.SyncSystem - SyncSystem.SyncSystemFieldMappings (m:1)'</summary>
		[DataMember]
		public virtual SyncSystem SyncSystem { get; set;}
		#endregion
	}
}
