//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'SyncSystemSettingValue'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class SyncSystemSettingValue : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="SyncSystemSettingValue"/> class.</summary>
		public SyncSystemSettingValue() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the SettingId field. </summary>
		[DataMember]
		public System.Int32 SettingId { get; set;}
		/// <summary>Gets or sets the SettingValue field. </summary>
		[DataMember]
		public System.String SettingValue { get; set;}
		/// <summary>Gets or sets the SyncSystemSettingId field. </summary>
		[DataMember]
		public System.Int32 SyncSystemSettingId { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystemSettingValue.SyncSystem - SyncSystem.SyncSystemSettingValues (m:1)'</summary>
		[DataMember]
		public virtual SyncSystem SyncSystem { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'SyncSystemSettingValue.SyncSystemSetting - SyncSystemSetting.SyncSystemSettingValues (m:1)'</summary>
		[DataMember]
		public virtual SyncSystemSetting SyncSystemSetting { get; set;}
		#endregion
	}
}
