//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'VProjectServerSystemLink'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class VProjectServerSystemLink : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="VProjectServerSystemLink"/> class.</summary>
		public VProjectServerSystemLink() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the DateCreated field. </summary>
		[DataMember]
		public System.DateTime DateCreated { get; set;}
		/// <summary>Gets or sets the EpicId field. </summary>
		[DataMember]
		public System.String EpicId { get; set;}
		/// <summary>Gets or sets the EpicKey field. </summary>
		[DataMember]
		public System.String EpicKey { get; set;}
		/// <summary>Gets or sets the EpicName field. </summary>
		[DataMember]
		public System.String EpicName { get; set;}
		/// <summary>Gets or sets the ExecuteStatus field. </summary>
		[DataMember]
		public System.String ExecuteStatus { get; set;}
		/// <summary>Gets or sets the IsHomeProject field. </summary>
		[DataMember]
		public System.Boolean IsHomeProject { get; set;}
		/// <summary>Gets or sets the LastExecuted field. </summary>
		[DataMember]
		public Nullable<System.DateTime> LastExecuted { get; set;}
		/// <summary>Gets or sets the ProjectId field. </summary>
		[DataMember]
		public System.String ProjectId { get; set;}
		/// <summary>Gets or sets the ProjectKey field. </summary>
		[DataMember]
		public System.String ProjectKey { get; set;}
		/// <summary>Gets or sets the ProjectName field. </summary>
		[DataMember]
		public System.String ProjectName { get; set;}
		/// <summary>Gets or sets the ProjectServerSystemLinkId field. </summary>
		[DataMember]
		public System.Int32 ProjectServerSystemLinkId { get; set;}
		/// <summary>Gets or sets the ProjectUid field. </summary>
		[DataMember]
		public System.Guid ProjectUid { get; set;}
		/// <summary>Gets or sets the RowNumber field. </summary>
		[DataMember]
		public System.Int32 RowNumber { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Gets or sets the SystemName field. </summary>
		[DataMember]
		public System.String SystemName { get; set;}
		#endregion
	}
}
