//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'VStagingFieldMappingValue'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class VStagingFieldMappingValue : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="VStagingFieldMappingValue"/> class.</summary>
		public VStagingFieldMappingValue() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the EpmFieldName field. </summary>
		[DataMember]
		public System.String EpmFieldName { get; set;}
		/// <summary>Gets or sets the FieldType field. </summary>
		[DataMember]
		public System.String FieldType { get; set;}
		/// <summary>Gets or sets the RowNumber field. </summary>
		[DataMember]
		public System.Int32 RowNumber { get; set;}
		/// <summary>Gets or sets the StagingFieldMappingValueId field. </summary>
		[DataMember]
		public Nullable<System.Int32> StagingFieldMappingValueId { get; set;}
		/// <summary>Gets or sets the StagingFieldName field. </summary>
		[DataMember]
		public System.String StagingFieldName { get; set;}
		/// <summary>Gets or sets the StagingId field. </summary>
		[DataMember]
		public Nullable<System.Int32> StagingId { get; set;}
		/// <summary>Gets or sets the SyncSystemFieldMappingId field. </summary>
		[DataMember]
		public Nullable<System.Int32> SyncSystemFieldMappingId { get; set;}
		/// <summary>Gets or sets the SystemFieldName field. </summary>
		[DataMember]
		public System.String SystemFieldName { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Gets or sets the Value field. </summary>
		[DataMember]
		public System.String Value { get; set;}
		#endregion
	}
}
