//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v4.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace ProjectOnlineSystemConnector.Data.Views.EntityClasses
{
	/// <summary>Class which represents the entity 'WebHookEntry'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class WebHookEntry : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="WebHookEntry"/> class.</summary>
		public WebHookEntry() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the DateCreated field. </summary>
		[DataMember]
		public System.DateTime DateCreated { get; set;}
		/// <summary>Gets or sets the JsonRequest field. </summary>
		[DataMember]
		public System.String JsonRequest { get; set;}
		/// <summary>Gets or sets the SystemId field. </summary>
		[DataMember]
		public System.Int32 SystemId { get; set;}
		/// <summary>Gets or sets the WebHookEntryId field. </summary>
		[DataMember]
		public System.Int32 WebHookEntryId { get; set;}
		/// <summary>Represents the navigator which is mapped onto the association 'WebHookEntry.SyncSystem - SyncSystem.WebHookEntries (m:1)'</summary>
		[DataMember]
		public virtual SyncSystem SyncSystem { get; set;}
		#endregion
	}
}
